rails_app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/pro/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'login', to: 'login#index', as: :new_user_session
    post 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # adds in a login_path route helper
  get 'login', to: 'login#index', as: :login

  scope :admin do
    get '/', to: 'admin#index', as: :admin
    resources :users
    resources :endpoints do
      member { post :harvest }
    end
    resources :aspace_instances
  end

  defaults format: :json do
    get '/api/endpoints', to: 'api#endpoints', as: :endpoints_api
    get '/api/repositories', to: 'api#repositories', as: :repositories_api
  end

  mount Blacklight::Engine => '/'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [], as: 'catalog', path: '/records',
                     controller: :catalog, constraints: { id: %r{[^/]+} } do
    concerns :searchable
  end

  # Legacy ID lookup route
  get '/records/legacy/:id', to: 'legacy#redirect'

  resources :solr_documents, only: [:show], path: '/records',
                             controller: :catalog, constraints: { id: %r{[^/]+} } do
    member { get '/ead', to: 'catalog#show', defaults: { format: 'ead' } } # get raw EAD XML
  end

  resources :requests, only: %i[create] do
    collection do
      post 'prepare'
    end
  end

  scope :status do
    get '/', to: 'status#index', as: :endpoints_status
    get '/:id', to: 'status#show', as: :endpoint_status
  end

  get 'repositories', to: 'catalog#repositories'
  get 'about', to: 'static_pages#about'
  get 'how-to-use', to: 'static_pages#how_to_use'

  # Vanity route for Penn materials
  get 'upenn', to: 'catalog#upenn'

  root to: 'catalog#index'
end

rails_app/app/models/endpoint.rb
# frozen_string_literal: true

# Represent a partner's endpoint from which we will harvest records
class Endpoint < ApplicationRecord
  include Synchronizable

  WEBPAGE_TYPE = 'webpage'
  ASPACE_TYPE = 'aspace'
  SOURCE_TYPES = [WEBPAGE_TYPE, ASPACE_TYPE].freeze

  validates :slug, presence: true, uniqueness: true, format: { with: /\A[A-Za-z_]+\z/ }
  validates :source_type, presence: true, inclusion: SOURCE_TYPES
  validates :webpage_url, presence: true, if: :webpage_type?
  validates :webpage_url, absence: true, if: :aspace_type?
  validates :aspace_repo_id, :aspace_instance, presence: true, if: :aspace_type?
  validates :aspace_repo_id, :aspace_instance, absence: true, if: :webpage_type?
  validates :active, inclusion: [true, false]

  belongs_to :aspace_instance, optional: true

  scope :is_active, -> { where(active: true) }

  def aspace_type?
    source_type == ASPACE_TYPE
  end

  def webpage_type?
    source_type == WEBPAGE_TYPE
  end

  def last_harvest
    @last_harvest ||= LastHarvest.new(last_harvest_results)
  end

  # URL to display in UI and mailers. We only display webpage type URLs because the ASpace hosts are locked down and
  # typically not generally resolvable.
  def display_url
    return unless webpage_type?

    webpage_url
  end

  # Wrapper for last_harvest_results providing accessor and helper methods.
  class LastHarvest
    PARTIAL = 'partial'
    COMPLETE = 'complete'
    FAILED = 'failed'
    STATUSES = [PARTIAL, COMPLETE, FAILED].freeze

    attr_reader :results

    def initialize(results)
      @results = results
    end

    # Returns last harvest status. If no harvest was run returns nil, otherwise
    # returns one of the following statuses:
    #   FAILED: if errors were raised when trying to retrieve the endpoint url
    #   PARTIAL: if at least one error was raised when trying to harvest an individual EAD
    #   COMPLETE: if endpoint url was successfully retrieved and all EADs listed were successfully harvested
    #
    # @return [String] status of harvest run
    # @return [nil] harvest was not run
    def status
      return nil if results.to_h.blank?
      return FAILED if errors&.any?
      return PARTIAL if problem_files.any?

      COMPLETE
    end

    STATUSES.each do |s|
      define_method "#{s}?" do
        status == s
      end
    end

    # Date and time harvest was run at.
    # @return [DateTime]
    def date
      results['date']
    end

    # Return errors that occurred when attempting to load and parse the Endpoint's URL
    # @return [Array]
    def errors
      results['errors']
    end

    # Return file information for those files referenced, downloaded and parsed from the Endpoint's URL
    # @return [Array]
    def files
      results['files']
    end

    # Return Array of file info for files unable to be harvested
    # @return [Array<Hash>]
    def problem_files
      @problem_files ||= Array.wrap(
        files&.select do |file|
          file['status'] == 'failed'
        end
      )
    end

    # Return Array of file info for files able to be harvested
    # @return [Array<Hash>]
    def success_files
      @success_files ||= Array.wrap(
        files&.select do |file|
          file['status'] == 'ok'
        end
      )
    end

    # Return Array of ids for records removed in the last harvest
    # @return [Array<Hash>]
    def removed_files
      @removed_files = Array.wrap(
        files&.select do |file|
          file['status'] == 'removed'
        end
      )
    end

    # Did the last harvest include any record removals?
    # @return [TrueClass, FalseClass]
    def removals?
      removed_files&.any?
    end
  end

  # @return [Object]
  def extractor
    @extractor ||= extractor_class.new(endpoint: self)
  end

  # Return Class for extracting XML File URLs from a source
  def extractor_class
    "#{source_type.camelize}Extractor".constantize
  end

  # @return [Object]
  def parser
    @parser ||= parser_class.new(self)
  end

  # Return Class for parsing xml_urls for this Endpoint
  # @note This function was originally written to extract the "parser" value from the harvest_config with the idea
  #   that we may need different parser classes for different records. The method will stay in place in case we
  #   need this functionality down the road.
  def parser_class
    EadParser
  end

  def reload
    @last_harvest = nil # Resetting last_harvest so the object is re-instantiated with fresh data.
    super
  end
end

rails_app/app/controllers/endpoints_controller.rb
# frozen_string_literal: true

# controller actions for Endpoints
class EndpointsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_endpoint, only: %w[show edit update harvest]
  before_action :load_aspace_instances, only: %w[new create edit update]

  layout 'application'

  def index
    @endpoints = Endpoint.page(params[:page])
  end

  def show; end

  def new
    @endpoint = Endpoint.new
  end

  def edit; end

  def create
    @endpoint = Endpoint.new(endpoint_params)
    if @endpoint.save
      notify_success action: :create, class_name: @endpoint.class, identifier: @endpoint.slug
      redirect_to endpoint_path(@endpoint)
    else
      alert_failure action: :create, class_name: @endpoint.class, identifier: @endpoint.slug,
                    error: @endpoint.errors.map(&:full_message).join(', ')
      render :new
    end
  end

  def update
    if @endpoint.update(endpoint_params.except(:slug))
      notify_success action: :update, class_name: @endpoint.class, identifier: @endpoint.slug
      redirect_to endpoint_path(@endpoint)
    else
      alert_failure action: :update, class_name: @endpoint.class, identifier: @endpoint.slug,
                    error: @endpoint.errors.map(&:full_message).join(', ')
      render :edit
    end
  end

  def destroy; end

  def harvest
    PartnerHarvestJob.perform_later @endpoint
    notify_success action: :harvest, class_name: @endpoint.class.name, identifier: @endpoint.slug
    redirect_to endpoint_path(@endpoint)
  rescue StandardError => e
    alert_failure action: :harvest, class_name: @endpoint.class.name, identifier: @endpoint.slug,
                  error: e.message
    redirect_to endpoint_path(@endpoint)
  end

  private

  def load_endpoint
    @endpoint = Endpoint.find(params[:id])
  end

  def load_aspace_instances
    @aspace_instances = ASpaceInstance.all
  end

  # @return [ActionController::Parameters]
  def endpoint_params
    prepare_contacts_params
    params.require(:endpoint).permit(:slug, { public_contacts: [] }, { tech_contacts: [] }, :source_type, :webpage_url,
                                     :aspace_repo_id, :aspace_instance_id, :active)
  end

  # @return [ActionController::Parameters]
  def prepare_contacts_params
    params[:endpoint][:public_contacts] = params[:endpoint][:public_contacts].split(',').map(&:strip)
    params[:endpoint][:tech_contacts] = params[:endpoint][:tech_contacts].split(',').map(&:strip)
  end
end

rails_app/app/helpers/endpoints_helper.rb
# frozen_string_literal: true

module EndpointsHelper
  # @param [NilClass, String] date
  # @return [String]
  def time_since_last_harvest(date)
    return 'Not harvested yet' if date.blank?

    "#{time_ago_in_words DateTime.parse(date), include_seconds: true} ago"
  end

  # @param [Hash] file
  # @return [String]
  def error_message_for(file)
    "#{file['id']}: #{file['errors'].join(', ')}"
  end

  # @param [Endpoint] endpoint
  # @return [String]
  def endpoint_active_class(endpoint)
    endpoint.active? ? 'text-success' : 'text-danger'
  end

  # @param [Endpoint] endpoint
  # @return [String]
  def table_active_class(endpoint)
    return 'table-danger' if endpoint.last_harvest.failed?
    return 'table-warning' unless endpoint.active?

    ''
  end
end

rails_app/app/views/endpoints/_form.html.erb
<%= bootstrap_form_for(@endpoint) do |f| %>
  <%= f.check_box :active, checked: @endpoint.active %>
  <%= f.text_field :slug, disabled: edit %>
  <%= f.text_field :public_contacts, value: @endpoint.public_contacts&.join(',') %>
  <%= f.text_field :tech_contacts, value: @endpoint.tech_contacts&.join(',') %>
  <%= f.select :source_type, @endpoint.class::SOURCE_TYPES %>
  <%= f.text_field :webpage_url %>
  <%= f.collection_select :aspace_instance_id, @aspace_instances, :id, :slug,
                          selected: @endpoint.aspace_instance&.id,
                          include_blank: t('admin.endpoints.aspace_instance.include_blank') %>
  <%= f.text_field :aspace_repo_id, label: t('admin.endpoints.aspace_repo_id') %>
  <%= f.submit 'Save' %>
<% end %>

rails_app/app/views/endpoints/edit.html.erb
<h1>Edit Endpoint <%= @endpoint.slug %></h1>

<%= render 'form', edit: true %>

rails_app/app/views/endpoints/index.html.erb
<h1>Endpoints</h1>

<div class="d-flex justify-content-end">
  <div class="btn-group mb-3">
    <%= link_to t('admin.actions.create'), new_endpoint_path, class: 'btn btn-outline-dark' %>
  </div>
</div>

<% if @endpoints.empty? %>
  <p>No endpoints yet!</p>
<% else %>
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">Slug</th>
      <th scope="col">Source Type</th>
      <th scope="col">Created At</th>
      <th scope="col">Updated At</th>
      <th scope="col">Active</th>
    </tr>
    </thead>
    <tbody>
    <% @endpoints.each do |endpoint| %>
      <tr class="row-id-<%= endpoint.id %>">
        <td class="slug"><%= link_to endpoint.slug, endpoint_path(endpoint) %></td>
        <td class="source_type"><%= endpoint.source_type %></td>
        <td class="created_at"><%= endpoint.created_at.to_fs(:display) %></td>
        <td class="updated_at"><%= endpoint.updated_at.to_fs(:display) %></td>
        <td class="active <%= endpoint_active_class(endpoint) %>">
          <%= endpoint.active.to_s.titleize %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= paginate @endpoints %>
<% end %>

rails_app/app/views/endpoints/new.html.erb
<h1>New Endpoint</h1>

<%= render 'form', edit: false %>

rails_app/app/views/endpoints/show.html.erb
<h1 class="mb-3">Endpoint Summary</h1>

<div class="btn-toolbar mb-3" role="toolbar" aria-label="Endpoint actions">
  <div class="btn-group mr-2" role="group" aria-label="Endpoint management">
    <%= link_to t('admin.actions.edit'), edit_endpoint_path(@endpoint), class: 'btn btn-outline-dark' %>
  </div>
  <div class="btn-group" role="group" aria-label="Endpoint jobs">
    <%= button_to t('admin.actions.harvest'), harvest_endpoint_path(@endpoint), class: 'btn btn-outline-info' %>
  </div>
</div>

<dl class="endpoint-list">
  <dt>Active</dt>
  <dd class="<%= endpoint_active_class(@endpoint) %>">
    <%= @endpoint.active.to_s.titleize %>
  </dd>

  <dt>Slug</dt>
  <dd><%= @endpoint.slug %></dd>

  <dt>Source Type</dt>
  <dd><%= @endpoint.source_type %></dd>

  <dt>Public Contacts</dt>
  <dd><%= @endpoint.public_contacts.join(', ') %></dd>

  <dt>Technical Contacts</dt>
  <dd><%= @endpoint.tech_contacts.join(', ') %></dd>

  <dt>Status</dt>
  <dd><%= link_to(t('admin.endpoints.last_harvest_results'), endpoint_status_path(@endpoint.slug)) %></dd>

  <% if @endpoint.webpage_type? %>
  <dt>Webpage URL</dt>
  <dd><%= link_to @endpoint.webpage_url, @endpoint.webpage_url %></dd>
  <% end %>

  <% if @endpoint.aspace_type? %>
    <dt>ASpace Instance</dt>
    <dd><%= link_to @endpoint.aspace_instance.slug, aspace_instance_path(@endpoint.aspace_instance) %></dd>

    <dt><%= I18n.t('admin.endpoints.aspace_repo_id') %></dt>
    <dd><%= @endpoint.aspace_repo_id %></dd>
  <% end %>

  <dt>Created At</dt>
  <dd><%= @endpoint.created_at.to_fs(:display) %></dd>

  <dt>Updated At</dt>
  <dd><%= @endpoint.updated_at.to_fs(:display) %></dd>
</dl>