rails_app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/pro/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'login', to: 'login#index', as: :new_user_session
    post 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # adds in a login_path route helper
  get 'login', to: 'login#index', as: :login

  scope :admin do
    get '/', to: 'admin#index', as: :admin
    resources :users
    resources :endpoints do
      member { post :harvest }
    end
    resources :aspace_instances
  end

  defaults format: :json do
    get '/api/endpoints', to: 'api#endpoints', as: :endpoints_api
    get '/api/repositories', to: 'api#repositories', as: :repositories_api
  end

  mount Blacklight::Engine => '/'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [], as: 'catalog', path: '/records',
                     controller: :catalog, constraints: { id: %r{[^/]+} } do
    concerns :searchable
  end

  # Legacy ID lookup route
  get '/records/legacy/:id', to: 'legacy#redirect'

  resources :solr_documents, only: [:show], path: '/records',
                             controller: :catalog, constraints: { id: %r{[^/]+} } do
    member { get '/ead', to: 'catalog#show', defaults: { format: 'ead' } } # get raw EAD XML
  end

  resources :requests, only: %i[create] do
    collection do
      post 'prepare'
    end
  end

  scope :status do
    get '/', to: 'status#index', as: :endpoints_status
    get '/:id', to: 'status#show', as: :endpoint_status
  end

  get 'repositories', to: 'catalog#repositories'
  get 'about', to: 'static_pages#about'
  get 'how-to-use', to: 'static_pages#how_to_use'

  # Vanity route for Penn materials
  get 'upenn', to: 'catalog#upenn'

  root to: 'catalog#index'
end

rails_app/app/views/shared/_admin_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"><%= t('admin.heading') %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to t('admin.menu.homepage'), root_url, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('admin.menu.users'), users_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to t('admin.menu.endpoints'), endpoints_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to t('admin.menu.aspace_instances'), aspace_instances_path, class: 'nav-link' %>
      </li>
<!--      <li class="nav-item">-->
        <%#= link_to t('admin.menu.endpoints'), endpoints_path, class: 'nav-link' %>
<!--      </li>-->
      <li class="nav-item">
        <%= link_to t('admin.menu.status'), endpoints_status_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to t('admin.menu.sidekiq'), sidekiq_web_path, class: 'nav-link', target: '_blank' %>
      </li>
    </ul>
    <%= button_to t('admin.menu.sign_out'), destroy_user_session_path, class: 'btn btn-link' %>
  </div>
</nav>

rails_app/app/views/shared/_flash_msg.html.erb
<%# Overridden from Blacklight 8.12.3 to to render close icon in Bootstrap 4. This should be removed once we
upgrade to Bootstrap 5. %>
<%# TODO: remove once upgraded to Bootstrap 5 %>
<div class="flash_messages">
  <% flash.each do |type, msg| %>
    <div class="alert alert-<%= type == 'notice' ? 'info' : 'warning' %>">
      <%= msg %>
      <a class="close" data-dismiss="alert" data-bs-dismiss="alert" href="#">&times;</a>
    </div>
  <% end %>
</div>

rails_app/app/views/shared/_fonts.html.erb
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gentium+Basic:ital,wght@0,400;0,700;1,400;1,700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

rails_app/app/views/shared/_footer.html.erb
<footer>
  <div class="footerliner one clearfix">
    <h2 class="bs4-visually-hidden" id="h2navfooter">Footer: Sitemap for navigation</h2>
    <h3 class="bs4-visually-hidden">Branding</h3>
    <div class="vlist branding">
      <div class="delivered"><%= t('footer.delivered_by') %></div>
      <a class="logo" href="https://www.library.upenn.edu"><%= image_tag("logo-2020-whitetite.svg", alt: "University of Pennsylvania Libraries homepage") %></a>
      <div class="copyright"><%= t('footer.copyright') %></div>
    </div>
    <h3 class="bs4-visually-hidden">Site info</h3>
    <ul class="no-list-style vlist info">
      <li><%= link_to t('common.links.home'), root_path %></li>
      <li><%= link_to t('common.links.browse_repositories'), repositories_path %></li>
      <li><%= link_to t('common.links.about'), about_path, class: "ext" %></li>
      <li><%= link_to t('common.links.how_to'), how_to_use_path, class: "ext" %></li>
      <% if current_user %>
      <li><%= link_to(t('common.links.admin'), admin_path, class: "ext") %></li>
      <% end %>
    </ul>
    <h3 class="bs4-visually-hidden">PACSCL</h3>
    <ul class="no-list-style vlist pacscl">
      <li><%= link_to t('footer.links.pacscl'), "https://www.pacscl.org/", class: "ext" %></li>
      <li><%= link_to t('footer.links.hidden_coll_init'), "https://hsp.org/hcipsar", class: "ext" %></li>
    </ul>
  </div>
  <div class="footerliner two">
    <h3 class="bs4-visually-hidden">Policy links</h3>
    <ul class="no-list-style hlist policy">
      <li class="disc"><%= link_to t('footer.links.disclaimer'), 'https://docs.google.com/document/d/17iZV-mBIqeDbHWFu-8Z4PAwA_-0Xi8OrNFOPVCsKcQQ/', class: 'ext' %></li>
      <li class="privacy"><%= link_to t('footer.links.privacy'), 'https://www.library.upenn.edu/about/policies/privacy', class: 'ext' %></li>
      <li class="acc"><%= link_to t('footer.links.a11y'), 'https://accessibility.web-resources.upenn.edu/get-help', class: 'ext' %></li>
      <li class="statement"><%= link_to t('footer.links.statement'), 'https://pacscl.org/what-we-believe/statement-on-archival-description-and-harmful-language/', class: 'ext' %></li>
    </ul>
  </div>
</footer>

rails_app/app/views/shared/_header_navbar.html.erb
<%# Override of Blacklight partial from 7.x. 8.x file now renders the configured HeaderComponent. We've made many header
    changes as part of our initial design. TODO: add a local HeaderComponent %>

<header class="sitebrand">
  <h1 class="sitename"><a href="/">Philadelphia Area Archives</a></h1>
</header>

<%= content_tag :div, class: 'navbar-search navbar navbar-light bg-light', role: 'navigation', aria: { label: t('blacklight.search.header') } do %>
  <div class="<%= container_classes %>">
    <%= render((blacklight_config&.view_config(document_index_view_type)&.search_bar_component || Blacklight::SearchBarComponent).new(
      url: search_action_url,
      advanced_search_url: search_action_url(action: 'advanced_search'),
      params: search_state.params_for_search.except(:qt),
      autocomplete_path: search_action_path(action: :suggest))) %>
  </div>
  <% if user_signed_in? %>
    <%= button_to "Sign Out", destroy_user_session_path, class: 'btn btn-secondary' %>
  <% end %>
<% end %>