rails_app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/pro/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'login', to: 'login#index', as: :new_user_session
    post 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  # adds in a login_path route helper
  get 'login', to: 'login#index', as: :login

  scope :admin do
    get '/', to: 'admin#index', as: :admin
    resources :users
    resources :endpoints do
      member { post :harvest }
    end
    resources :aspace_instances
  end

  defaults format: :json do
    get '/api/endpoints', to: 'api#endpoints', as: :endpoints_api
    get '/api/repositories', to: 'api#repositories', as: :repositories_api
  end

  mount Blacklight::Engine => '/'
  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [], as: 'catalog', path: '/records',
                     controller: :catalog, constraints: { id: %r{[^/]+} } do
    concerns :searchable
  end

  # Legacy ID lookup route
  get '/records/legacy/:id', to: 'legacy#redirect'

  resources :solr_documents, only: [:show], path: '/records',
                             controller: :catalog, constraints: { id: %r{[^/]+} } do
    member { get '/ead', to: 'catalog#show', defaults: { format: 'ead' } } # get raw EAD XML
  end

  resources :requests, only: %i[create] do
    collection do
      post 'prepare'
    end
  end

  scope :status do
    get '/', to: 'status#index', as: :endpoints_status
    get '/:id', to: 'status#show', as: :endpoint_status
  end

  get 'repositories', to: 'catalog#repositories'
  get 'about', to: 'static_pages#about'
  get 'how-to-use', to: 'static_pages#how_to_use'

  # Vanity route for Penn materials
  get 'upenn', to: 'catalog#upenn'

  root to: 'catalog#index'
end

rails_app/app/controllers/catalog_controller.rb
# frozen_string_literal: true

# Blacklight controller configuring search and record pages.
class CatalogController < ApplicationController
  include Blacklight::Catalog

  configure_blacklight do |config|
    config.bootstrap_version = 4

    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response
    #
    ## Should the raw solr document endpoint (e.g. /catalog/:id/raw) be enabled
    # config.raw_endpoint.enabled = false

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = { rows: 10 }

    # disable tracking links since we don't allow paginating through a results set
    config.track_search_session = Blacklight::OpenStructWithHashAccess.new({ storage: false })

    # solr path which will be added to solr base url before the other solr params.
    # config.solr_path = 'select'
    # config.document_solr_path = 'get'

    # items to show per page, each number in the array represent another option to choose from.
    config.per_page = [10, 20, 50, 100]

    # Use local Document component to customize results and show page views
    config.index.document_component = Catalog::ResultsDocumentComponent
    config.show.document_component = Catalog::ShowDocumentComponent

    # Use custom DocumentTitleComponent on results page
    config.index.title_component = Catalog::DocumentTitleComponent
    # TODO: we've found that setting this is required, even though it should be the default. otherwise the setting from
    #       above applies in show contexts as well. this could be a blacklight bug, or by using distinct
    #       DocumentComponents.
    config.show.title_component = Blacklight::DocumentTitleComponent

    # solr field configuration for search results/index views
    config.index.title_field = :title_tsi
    # config.index.display_type_field = 'format'
    # config.index.thumbnail_field = 'thumbnail_path_ss'

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    # solr field configuration for document/show views
    # config.show.title_field = :title_tsi
    # config.show.display_type_field = 'format'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically
    #   across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation
    #              (note: It is case sensitive when searching values)

    config.add_facet_field 'repository_ssi', label: I18n.t('fields.repository'), limit: true
    config.add_facet_field 'record_source', label: I18n.t('fields.record_source'), query: {
      upenn: { label: 'University of Pennsylvania', fq: 'upenn_record_bsi:true' },
      non_upenn: { label: 'Other PACSCL Partners', fq: 'upenn_record_bsi:false' }
    }
    config.add_facet_field 'online_content', label: I18n.t('fields.online_content'), query: {
      yes: { label: 'Has Online Content', fq: 'online_content_bsi:true' },
      no: { label: 'Not Available', fq: 'online_content_bsi:false' }
    }
    config.add_facet_field 'subjects_ssim', label: I18n.t('fields.topics.subjects'), limit: true
    config.add_facet_field 'corpnames_ssim', label: I18n.t('fields.topics.corpnames'), limit: true
    config.add_facet_field 'people_ssim', label: I18n.t('fields.topics.people'), limit: true
    config.add_facet_field 'places_ssim', label: I18n.t('fields.topics.places'), limit: true
    config.add_facet_field 'occupations_ssim', label: I18n.t('fields.topics.occupations'), limit: true
    config.add_facet_field 'genre_form_ssim', label: I18n.t('fields.genre_form'), limit: true
    config.add_facet_field 'creators_ssim', label: I18n.t('fields.creators'), limit: true
    config.add_facet_field 'donors_ssim', label: I18n.t('fields.donors'), limit: true
    config.add_facet_field 'languages_ssim', label: I18n.t('fields.language'), limit: true
    config.add_facet_field 'era_facet', label: I18n.t('facets.era.label'), solr_params:
      { 'facet.mincount': 1 }, query: {
        first_millennium: { label: I18n.t('facets.era.millennium.first'), fq: 'years_iim:[0001 TO 1000]' },
        eleventh_century: { label: I18n.t('facets.era.century.eleventh'), fq: 'years_iim:[1001 TO 1100]' },
        twelfth_century: { label: I18n.t('facets.era.century.twelfth'), fq: 'years_iim:[1101 TO 1200]' },
        thirteenth_century: { label: I18n.t('facets.era.century.thirteenth'), fq: 'years_iim:[1201 TO 1300]' },
        fourteenth_century: { label: I18n.t('facets.era.century.fourteenth'), fq: 'years_iim:[1301 TO 1400]' },
        fifteenth_century: { label: I18n.t('facets.era.century.fifteenth'), fq: 'years_iim:[1401 TO 1500]' },
        sixteenth_century: { label: I18n.t('facets.era.century.sixteenth'), fq: 'years_iim:[1501 TO 1600]' },
        seventeenth_century: { label: I18n.t('facets.era.century.seventeenth'), fq: 'years_iim:[1601 TO 1700]' },
        eighteenth_century: { label: I18n.t('facets.era.century.eighteenth'), fq: 'years_iim:[1701 TO 1800]' },
        nineteenth_century: { label: I18n.t('facets.era.century.nineteenth'), fq: 'years_iim:[1801 TO 1900]' },
        twentieth_century: { label: I18n.t('facets.era.century.twentieth'), fq: 'years_iim:[1901 TO 2000]' },
        twenty_first_century: { label: I18n.t('facets.era.century.twenty-first'), fq: 'years_iim:[2001 TO 2100]' }
      }
    config.add_facet_field 'endpoint_ssi', label: I18n.t('fields.endpoint'), limit: true, unless: Rails.env.production?

    config.add_facet_fields_to_solr_request!

    config.add_index_field 'title_tsi', label: I18n.t('fields.title'), if: :json_request?
    config.add_index_field 'extent_ssim', label: I18n.t('fields.extent')
    config.add_index_field 'display_date_ssim', label: I18n.t('fields.date'), if: :json_request?
    config.add_index_field 'subjects_ssim', label: I18n.t('fields.topics.subjects'), if: :json_request?
    config.add_index_field 'genre_form_ssim', label: I18n.t('fields.genre_form'), if: :json_request?
    config.add_index_field 'creators_ssim', label: I18n.t('fields.creators'), if: :json_request?
    config.add_index_field 'repository_ssi', label: I18n.t('fields.repository'), if: :json_request?
    config.add_index_field 'abstract_scope_contents_tsi', label: I18n.t('fields.abstract_scope_contents'),
                                                          helper_method: :truncated_abstract

    config.add_show_field 'pretty_unit_id_ss', label: I18n.t('fields.pretty_unit_id')
    config.add_show_field 'repository_ssi', label: I18n.t('fields.repository'), link_to_facet: true
    config.add_show_field 'url_ss', label: I18n.t('fields.url')
    config.add_show_field 'extent_ssim', label: I18n.t('fields.extent'), helper_method: :extent_display
    config.add_show_field 'languages_ssim', label: I18n.t('fields.language'), link_to_facet: true
    config.add_show_field 'language_note', label: I18n.t('fields.language_note'), accessor: :language_note,
                                           if: :render_language_note?
    config.add_show_field 'preferred_citation_ss', label: I18n.t('fields.citation')
    config.add_show_field 'display_date_ssim', label: I18n.t('fields.date')
    config.add_show_field 'creators_ssim', label: I18n.t('fields.creators'), link_to_facet: true
    config.add_show_field 'donors_ssim', label: I18n.t('fields.donors'), link_to_facet: true
    config.add_show_field 'genre_form_ssim', label: I18n.t('fields.genre_form'), link_to_facet: true
    config.add_show_field 'abstract_scope_contents_tsi', label: I18n.t('fields.abstract_scope_contents')
    config.add_show_field 'xml_ss', label: I18n.t('fields.xml'), if: :json_request?

    config.add_search_field 'all_fields', label: 'All Fields'

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the Solr field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case). Add the sort: option to configure a
    # custom Blacklight url parameter value separate from the Solr sort fields.
    config.add_sort_field 'relevance', sort: 'score desc', label: I18n.t('sorts.relevance')

rails_app/app/views/catalog/_home_text.html.erb
<h1 class="hptitle"><%= t('homepage.header') %></h1>
<h2 class="bs4-visually-hidden">Main content</h2>
<div class="hpcontent">
  <p>
    This Philadelphia Area Archives site, formerly the Philadelphia Area Archives Research Portal (PAARP) and
    <%= link_to 'PACSCL', 'https://pacscl.org', class: 'ext' %> Finding Aids Site, provides access
    to descriptions of more than 5,000 collections from over 200 regional institutions documenting the region's vital
    role in our collective history, from colonization to the present day, from the everyday citizen to some of America's
    best known thinkers and celebrated citizens. On this site, researchers will find catalog descriptions, or "finding
    aids," to collections relating to local, national, and world history; the natural and social sciences; medicine;
    literature; religion; art and architecture; business and industry; the performing arts; and other topics.
  </p>

  <p>
    Searchable by creator, topic, repository, and keyword, this diverse and ever-growing group of finding aids is an
    ideal starting point for researchers to discover related collections across more than 200 regional repositories,
    large and small.
  </p>

  <p>
    When describing archival collections, staff at archival repositories make choices about what language to use when
    describing not just the papers and records, but also the people and organizations who created or who are
    represented in them. For a variety of reasons, researchers may encounter outdated language in the finding aids
    of PACSCL member institutions. For more information, go to
    <%= link_to 'PACSCL.org',
                'https://pacscl.org',
                class: 'ext' %>.
  </p>
</div>

<ul class="hplinks no-list-style clearfix">
  <li class="how-to"><%= link_to t('common.links.how_to'), how_to_use_path %></li>
  <li class="browse-rep"><%= link_to t('common.links.browse_repositories'), repositories_path %></li>
  <li class="all"><%= link_to t('homepage.links.see_all'), search_catalog_path(search_field: 'all_fields', q: '') %></li>
</ul>

rails_app/app/views/catalog/_show_main_content.html.erb
<!-- copied from Blacklight 8.12.3, customized to render many additional sections -->

<%= render blacklight_config.view_config(:show).document_header_component.new(document: @document, search_context: @search_context, search_session: search_session) %>
<% @page_title = t('blacklight.search.show.title', document_title: document_presenter(@document).html_title, application_name: application_name).html_safe %>
<% content_for(:head) { render_link_rel_alternates } %>

<% document_component = blacklight_config.view_config(:show).document_component -%>
<%= render (document_component).new(document: document_presenter(@document), component: :div, show: true, partials: blacklight_config.view_config(:show).partials) do |component| %>
  <% component.with_title(as: 'h1', link_to_document: false, actions: false) %>
  <% component.with_footer do %>
    <% if @document.respond_to?(:export_as_openurl_ctx_kev) %>
      <!-- COinS, for Zotero among others. -->
      <span class="Z3988" title="<%= @document.export_as_openurl_ctx_kev(document_presenter(@document).display_type) %>"></span>
    <% end %>
  <% end %>


  <% SolrDocument::ParsedEad::OTHER_SECTIONS.each do |section| %>
    <% open = %w[bioghist scopecontent arrangement].include?(section) %>
    <% component.with_collapsable_metadata_section(title: I18n.t(section, scope: :sections), open: open) do %>
      <%= render AdditionalMetadataComponent.new(nodes: @document.parsed_ead.try(section)) %>
    <% end %>
  <% end %>

  <% component.with_collapsable_metadata_section(title: t('sections.topics')) do %>
    <%= render TopicsComponent.new topics: @document.topics_hash %>
  <% end %>

  <% component.with_collapsable_metadata_section(title: t('sections.admin_info')) do %>
    <%= render AdministrativeInformationComponent.new sections: SolrDocument::ParsedEad::ADMIN_INFO_SECTIONS, document: @document %>
  <% end %>

  <% component.with_collection_inventory do %>
    <% if @document.requestable? %>
      <form id="requestItemsForm" class="form" action="<%= requests_path %>" method="POST">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <div class="sticky-top bg-light p-4 mb-3">
          <div id="requestingInfo" class="row justify-content-between align-items-center">
            <div class="col-sm-12 col-md-8">
              <strong>Request to View Materials</strong>
              <p class="instructions">Materials can be requested by first <%= link_to 'logging in to Aeon', AeonRequest::AEON_URL, class: 'ext', target: '_blank', rel: 'noopener' %>. Then, click on the ADD button next
                to any containers you wish to request. When complete, click the Request button.</p>
            </div>
            <div class="col-sm-12 col-md-2">
              <span class="float-right">
                <input id="submit-request" type="submit" value="Request" class="btn btn-primary" disabled>
              </span>
            </div>
          </div>
        </div>
        <fieldset>
          <legend class="bs4-visually-hidden">Request item to view</legend>
          <%= render CollectionsComponent.new(node: @document.parsed_ead.dsc, level: 1, requestable: true) %>
        </fieldset>
        <input type="hidden" name="call_num" value="<%= @document.requesting_info[:call_num] %>">
        <input type="hidden" name="repository" value="<%= @document.requesting_info[:repository] %>">
        <input type="hidden" name="title" value="<%= @document.requesting_info[:title] %>">
      </form>
    <% else %>
      <%= render(CollectionsComponent.new(node: @document.parsed_ead.dsc, requestable: @document.requestable? ,level: 1)) %>
    <% end %>
  <% end %>

  <% component.body do %>
    <div id="doc_<%= @document.id.to_s.parameterize %>">
      <%= render_document_partials @document, blacklight_config.view_config(:show).partials, component: component %>
    </div>
  <% end %>
<% end %>

rails_app/app/views/catalog/repositories.html.erb
<%#
    This template was inspired by the Blacklight template at: app/views/catalog/facet.html.erb
%>

<% @page_title = t('blacklight.repositories.page_title', application_name: application_name) %>

<%= render Blacklight::System::ModalComponent.new do |component| %>
  <% component.with_prefix do %>
    <div class="facet-pagination top row justify-content-end">
      <div class="sort-options btn-group">
        <% if @presenter.paginator.sort == 'index' %>
          <span class="active az btn btn-outline-secondary"><%= t('blacklight.search.facets.sort.index') %></span>
          <%= link_to(t('blacklight.search.facets.sort.count'), url_for(params: { 'facet.sort': 'count' }), class: "sort_change numeric btn btn-outline-secondary") %>
        <% elsif @presenter.paginator.sort == 'count' %>
          <%= link_to(t('blacklight.search.facets.sort.index'), url_for(params: { 'facet.sort': 'index' }), class: "sort_change az btn btn-outline-secondary") %>
          <spann class="active numeric btn btn-outline-secondary"><%= t('blacklight.search.facets.sort.count') %></spann>
        <% end %>
      </div>
    </div>
  <% end %>

  <% component.with_title { t('labels.titles.repositories_list') } %>

  <div class="facet-extended-list">
    <%= render Blacklight::FacetComponent.new(
      display_facet: @display_facet,
      field_config: @facet_config,
      layout: false
    ) %>
  </div>
<% end %>